image: atlassian/default-image:4
options:
  docker: true

definitions:
  caches:
    clis: "~/.clicache"

  steps:
    - step: &dockerBuild
        name: 'docker-build: Build zope docker image'
        script:
          - echo "build docker"
          - echo "Docker User $DOCKER_HUB_USER"
        services:
          - docker
        caches:
          - docker
    - step: &pyTest
        name: 'Run Pytest'
        caches:
          - pip
        script:
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - pip install pytest
          - pytest -v tests/* --junitxml=test-reports/report.xml
    - step: &pyLint
        name: Lint code
        caches:
          - pip
        cript:
          # Enforce style consistency across Python projects https://flake8.pycqa.org
          - pip install ruff
          - ruff check app/*.py

pipelines:
  default:
    - parallel:
      - step: *pyTest
      - step: *pyLint
      - step: *dockerBuild

  branches:
    main:
    - parallel:
      - step: *dockerBuild
